
name: Node.js CI

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run extract-tokens
      env:
        CI: true
